-- usatf schema DDL
-- Generated by export_ddl.py

CREATE SCHEMA IF NOT EXISTS usatf;

CREATE TABLE usatf.age_grade (
    sex varchar(1),
    age int4,
    _1_00 int4,
    _3_11 int4,
    _3_73 int4,
    _4_00 int4,
    _4_97 int4,
    _5_00 int4,
    _6_21 int4,
    _7_46 int4,
    _9_32 int4,
    _10_00 int4,
    _12_43 int4,
    _13_10 int4,
    _15_53 int4,
    _18_64 int4,
    _26_20 int4,
    _31_07 int4,
    _50_00 int4,
    _62_14 int4,
    _93_21 int4,
    _100_00 int4,
    _124_27 int4
);

CREATE TABLE usatf.events (
    id int4 NOT NULL,
    name varchar(),
    date date,
    location varchar(),
    dist_mi numeric,
    tab_name varchar(),
    col_name varchar()
);
ALTER TABLE usatf.events ADD CONSTRAINT events_pk PRIMARY KEY (id);

CREATE TABLE usatf.individual (
    event_id int4 NOT NULL,
    overall_race_rank int4,
    runner varchar() NOT NULL,
    gender varchar(),
    age int4,
    team varchar(),
    time varchar(),
    time_in_millis int4,
    age_grade varchar(),
    age_grade_rank int4,
    gender_rank int4,
    open_rank int4,
    masters_rank int4,
    grandmasters_rank int4,
    seniors_rank int4,
    open_m_rank int4,
    open_f_rank int4,
    masters_m_rank int4,
    masters_f_rank int4,
    grandmasters_m_rank int4,
    grandmasters_f_rank int4,
    seniors_m_rank int4,
    seniors_f_rank int4
);
ALTER TABLE usatf.individual ADD CONSTRAINT individual_pk PRIMARY KEY (event_id, runner);
ALTER TABLE usatf.individual ADD CONSTRAINT individual_event_id_fkey FOREIGN KEY (event_id) REFERENCES usatf.events (id);

CREATE TABLE usatf.individual_points (
    event_id int4 NOT NULL,
    division varchar() NOT NULL,
    gender varchar(),
    rank int4,
    points int4,
    runner varchar() NOT NULL,
    team varchar(),
    age int4,
    time varchar(),
    time_in_millis int4
);
ALTER TABLE usatf.individual_points ADD CONSTRAINT individual_points_pk PRIMARY KEY (event_id, division, runner);
ALTER TABLE usatf.individual_points ADD CONSTRAINT individual_points_event_id_fkey FOREIGN KEY (event_id) REFERENCES usatf.events (id);

CREATE TABLE usatf.members (
    first_name varchar() NOT NULL,
    last_name varchar() NOT NULL,
    sex varchar(1),
    age int4 NOT NULL,
    team varchar(),
    division varchar(),
    created_at timestamp
);
ALTER TABLE usatf.members ADD CONSTRAINT members_pk PRIMARY KEY (first_name, last_name, age);

CREATE TABLE usatf.results (
    event_id int4 NOT NULL,
    first_name varchar(),
    last_name varchar(),
    name varchar() NOT NULL,
    place varchar(),
    sex varchar(),
    age varchar(),
    time varchar(),
    time_in_millis int4
);
ALTER TABLE usatf.results ADD CONSTRAINT results_pk PRIMARY KEY (event_id, name);
ALTER TABLE usatf.results ADD CONSTRAINT results_event_id_fkey FOREIGN KEY (event_id) REFERENCES usatf.events (id);

CREATE TABLE usatf.team_individual (
    event_id int4 NOT NULL,
    division varchar() NOT NULL,
    gender varchar(),
    rank int4,
    team varchar(),
    team_time varchar(),
    team_time_in_millis int4,
    overall_race_rank int4,
    runner varchar() NOT NULL,
    age int4,
    time varchar(),
    time_in_millis int4
);
ALTER TABLE usatf.team_individual ADD CONSTRAINT team_individual_pk PRIMARY KEY (event_id, division, runner);
ALTER TABLE usatf.team_individual ADD CONSTRAINT team_individualevent_id_fkey FOREIGN KEY (event_id) REFERENCES usatf.events (id);

CREATE TABLE usatf.team_points (
    event_id int4 NOT NULL,
    division varchar() NOT NULL,
    gender varchar() NOT NULL,
    rank int4,
    team varchar() NOT NULL,
    team_points int4
);
ALTER TABLE usatf.team_points ADD CONSTRAINT team_points_pk PRIMARY KEY (event_id, division, gender, team);
ALTER TABLE usatf.team_points ADD CONSTRAINT team_points_event_id_fkey FOREIGN KEY (event_id) REFERENCES usatf.events (id);


-- Views

CREATE OR REPLACE VIEW usatf.v_team_division_gender_totals AS
 SELECT division,
    gender,
    team,
    sum(team_points) AS total_points,
    rank() OVER (PARTITION BY division, gender ORDER BY (sum(team_points)) DESC) AS team_rank
   FROM usatf.team_points
  GROUP BY division, gender, team
  ORDER BY division, gender, (rank() OVER (PARTITION BY division, gender ORDER BY (sum(team_points)) DESC));

CREATE OR REPLACE VIEW usatf.v_team_division_totals AS
 SELECT division,
    team,
    sum(team_points) AS total_points,
    rank() OVER (PARTITION BY division ORDER BY (sum(team_points)) DESC) AS team_rank
   FROM usatf.team_points
  GROUP BY division, team
  ORDER BY division, (rank() OVER (PARTITION BY division ORDER BY (sum(team_points)) DESC));

CREATE OR REPLACE VIEW usatf.v_team_event_division_gender_totals AS
 SELECT event_id,
    division,
    gender,
    team,
    sum(team_points) AS total_points,
    rank() OVER (PARTITION BY event_id, division, gender ORDER BY (sum(team_points)) DESC) AS team_rank
   FROM usatf.team_points
  GROUP BY event_id, division, gender, team
  ORDER BY event_id, division, gender, (rank() OVER (PARTITION BY event_id, division ORDER BY (sum(team_points)) DESC));

CREATE OR REPLACE VIEW usatf.v_team_event_division_totals AS
 SELECT event_id,
    division,
    team,
    sum(team_points) AS total_points,
    rank() OVER (PARTITION BY event_id, division ORDER BY (sum(team_points)) DESC) AS team_rank
   FROM usatf.team_points
  GROUP BY event_id, division, team
  ORDER BY event_id, division, (rank() OVER (PARTITION BY event_id, division ORDER BY (sum(team_points)) DESC));

CREATE OR REPLACE VIEW usatf.v_team_totals AS
 SELECT team,
    sum(team_points) AS total_points,
    rank() OVER (ORDER BY (sum(team_points)) DESC) AS team_rank
   FROM usatf.team_points
  GROUP BY team
  ORDER BY (rank() OVER (ORDER BY (sum(team_points)) DESC));

